### PR TITLE
Add ability to load auth from .dockercfg

### LINKED ISSUE #20: client: implement SetAuthConfig
http://docs.docker.io/en/latest/api/docker_remote_api/#set-auth-configuration

### PR DESCRIPTION
**Pull request by bmarini**
This fixes #20

### CODE REVIEW

**Comment by ejholmes** [comment]
+1

**Comment by fsouza** [comment]
Such a nice approach, I'm probably going to merge it. Testing locally.

Thanks for contributing!

**Comment by bmarini** [comment]
Thanks for this project!

**Comment by fsouza** [comment]
Just some nitpicks related to the code style, I will handle them myself:

* add the copyright note to the top of the file
* remove some blank lines inside functions and methods
* cut documentation comments at 80 columns

I'd also like to have a test for the ``NewAuthConfigurationsFromDockerCfg`` function, but we should not mess with the user filesystem just to have another test, so let's go this way.

Thank you very much for contributing!

**Comment by bmarini** [comment]
Awesome, thanks for being to responsive @fsouza ! I'll keep that in mind for my next PR.

**Pull request merged**
