### PR TITLE
container: Parse ExecIDs when inspecting

### PR DESCRIPTION
**Pull request by fgrehm**
Dunno for sure in which version this got added but I guess it doesn't matter :-)

### CODE REVIEW

**Comment by fsouza** [comment]
Yeah, the way we parse the output doesn't matter, it will just be nil when absent. Can you remove that blank line? I think we can go without it.

Thanks for contributing, again!

**Comment by fgrehm** [comment]
Remove blank line + `go fmt ./...`?

**Comment by fsouza** [comment]
Yes, please!

Thank you.

**Comment by fgrehm** [comment]
Amended and pushed to my branch! Feel free to :shipit: :smile:

**Comment by fsouza** [comment]
Thanks!

**Pull request merged**
