### PR TITLE
context support in APIs

### PR DESCRIPTION
**Pull request by ccp0101**
Implements https://github.com/fsouza/go-dockerclient/issues/516

At Meteor we wanted inflight API request cancellations, so we added context support to both synchronous and streaming clients. We only added context to a few top-level image APIs that we use, but I can add the rest, if this is a good approach @fsouza. The contexts are passed in APIOptions.

### CODE REVIEW

**Comment by fsouza** [comment]
Hi @ccp0101, thanks for contributing and sorry for keeping this PR hanging for so long. I'm planning to work on PRs #547 and #552 today or tomorrow (as they're somehow related).

**Comment by fsouza** [comment]
Hey @ccp0101, thanks for contributing! I really liked the approach you took, please feel free to extend it to other methods.

I wonder if we should use a build tag to use the context package that comes in the standard library in Go 1.7. What do you think?

**Comment by fsouza** [comment]
Never mind, using the build tag would make stuff too complex, we may change the code in the future to use just the package in the stdlib, but right now we can live with ``golang.org/x/net``. Thanks!

**Comment by ccp0101** [comment]
@fsouza great! Do you want me to add context to other APIs or do you want to do that after merging?

**Comment by fsouza** [comment]
@ccp0101 I'd prefer to have it before merging, but please let me know if it will taking too much of your time, so I can merge and help.

**Comment by glasser** [comment]
I think @ccp0101 is about to be traveling for a few weeks, so as his coworker who is happily using his fork but would like to unfork, I'd vote for the latter :)

**Comment by fsouza** [comment]
@glasser sounds good! I'm going to merge this one and extend the same approach to other methods in the API.

Thanks for the heads up

**Pull request merged**
