### PR TITLE
Add a method to remove networks

### PR DESCRIPTION
**Pull request by achanda**
Also add tests

### CODE REVIEW

**Comment by achanda** [comment]
@fsouza I'm not very sure why this fails in the CI. `make test` runs fine on my box, with go 1.5.1. Any ideas?

**Comment by fsouza** [comment]
@achanda seems like your code is indented with spaces instead of tabs, and gofmt doesn't approve that. I don't know why it doesn't fail on your local box, but it should :-(

Can you fix the indentation (running ``gofmt -s -w .`` is enough) and also the short link? I know that there isn't any documentation for the network API yet, so you can reuse the link from the [CreateNetwork](https://godoc.org/github.com/fsouza/go-dockerclient#Client.CreateNetwork) docs.

**Comment by achanda** [comment]
@fsouza thanks, my editor is set to expand tabs to spaces. I checked that the link matches that in CreateNetworks. Should be good now.

**Comment by fsouza** [comment]
@achanda I've just checked the link and it still points to the CreateContainer call, seems like CreateNetwork is broken as well, but CreateNetworkOptions is right.

Could you please update both the CreateNetwork and the DeleteNetwork linsk to match the same in CreateNetworkOptions? (https://goo.gl/FDkCdQ instead of http://goo.gl/mErxNp)

Thank you!

**Comment by fsouza** [comment]
@achanda I think that after updating the link you got back to the spaces vs tabs issue. Please run ``gofmt -s -w .`` again and I think we're good to get it merged!

**Comment by achanda** [comment]
@fsouza sorry, my vim is configured for python!

**Comment by fsouza** [comment]
@achanda no problem!

I recommend using vim-go: https://github.com/fatih/vim-go. It has a lot of interesting stuff :-)

**Comment by fsouza** [comment]
Seems like it didn't work hahah I will merge it and fix locally.

Thanks for contributing!

**Comment by achanda** [comment]
@fsouza thanks and sorry about that! vim-go looks like what I need :)

**Pull request merged**
