### PR TITLE
Logs(): add note on how to parse log streams

### PR DESCRIPTION
**Pull request by ahmetalpbalkan**

### CODE REVIEW

**Comment by fsouza** [comment]
Hey @ahmetalpbalkan, go-dockerclient should be able to multiplex the response (if ``RawTerminal`` is ``false``).

I must admit that I haven't _actually_ used ``Logs`` (only ``Attach``), so I want to ask: did you find any issues using Logs with ``RawTerminal=true``?

**Comment by ahmetalpbalkan** [comment]
@fsouza I see it now. It looks like setting RawTerminal uses stdcopy logic directly from docker/docker. So I guess we don’t need it here. You can close it if you like.

**Comment by fsouza** [comment]
I can improve the documentation to mention that when RawTerminal is set to true, go-dockerclient won't parse the output and multiplex the stream, and that dlog can be used in this case. What do you think?

**Comment by ahmetalpbalkan** [comment]
Sounds very good. Thanks.

**Pull request closed without merging**
