### PR TITLE
fix a bug contaienr.go Container unmarshal error

### PR DESCRIPTION
**Pull request by cst05001**
# fix a bug contaienr.go Container unmarshal error

## problem

error: json: cannot unmarshal object into Go value of type string

## root cause

error struct define

## test code

	package controllers
	
	import (
	    "fmt"
	    "encoding/json"
	    "io/ioutil"
	        "github.com/astaxie/beego"
	    "github.com/cst05001/go-dockerclient"
	)
	
	type TestController struct {
	        beego.Controller
	}
	
	func (this *TestController) Get() {
	    data, _:= ioutil.ReadFile("containerconfig/validatorscheduler.json")
	    container := &docker.Container{}
	    container.Config = &docker.Config{}
	    if err := json.Unmarshal(data, container); err != nil {
	        beego.Error(err)
	    }
	    beego.Debug(container)
	    beego.Debug("ExposedPorts:\n")
	    for k, v := range container.Config.ExposedPorts {
	        beego.Debug(fmt.Sprintf("%s: %s\n", k, v))
	    }
	    beego.Debug("Volumes:\n")
	    for k, v := range container.Config.Volumes {
	        beego.Debug(fmt.Sprintf("%s: %s\n", k, v))
	    }
	}

## data

[https://docs.docker.com/reference/api/docker_remote_api_v1.17/#create-a-container][1]

    POST /containers/create HTTP/1.1
    Content-Type: application/json

    {
         "Hostname": "",
         "Domainname": "",
         "User": "",
         "Memory": 0,
         "MemorySwap": 0,
         "CpuShares": 512,
         "Cpuset": "0,1",
         "AttachStdin": false,
         "AttachStdout": true,
         "AttachStderr": true,
         "Tty": false,
         "OpenStdin": false,
         "StdinOnce": false,
         "Env": null,
         "Cmd": [
                 "date"
         ],
         "Entrypoint": "",
         "Image": "ubuntu",
         "Volumes": {
                 "/tmp": {}
         },
         "WorkingDir": "",
         "NetworkDisabled": false,
         "MacAddress": "12:34:56:78:9a:bc",
         "ExposedPorts": {
                 "22/tcp": {}
         },
         "SecurityOpts": [""],
         "HostConfig": {
           "Binds": ["/tmp:/tmp"],
           "Links": ["redis3:redis"],
           "LxcConf": {"lxc.utsname":"docker"},
           "PortBindings": { "22/tcp": [{ "HostPort": "11022" }] },
           "PublishAllPorts": false,
           "Privileged": false,
           "ReadonlyRootfs": false,
           "Dns": ["8.8.8.8"],
           "DnsSearch": [""],
           "ExtraHosts": null,
           "VolumesFrom": ["parent", "other:ro"],
           "CapAdd": ["NET_ADMIN"],
           "CapDrop": ["MKNOD"],
           "RestartPolicy": { "Name": "", "MaximumRetryCount": 0 },
           "NetworkMode": "bridge",
           "Devices": []
        }
    }

[1]: https://docs.docker.com/reference/api/docker_remote_api_v1.17/#create-a-container

## fix

change container.go Container struct
Volumes from map[string]string to  map[string]struct{}

### CODE REVIEW

**Comment by fsouza** [comment]
Hi, thanks for contributing. Since the build is broken, I will take over this change and apply it.

Thank you again!

**Comment by fsouza** [comment]
Hi @cst05001, which Docker version you're using?

**Comment by cst05001** [comment]
I am using docker 1.4.1,
I write management tool myself. Using docker online API 1.6.

**Comment by fsouza** [comment]
@cst05001 from what I can see, you're trying to unmarshal Config into a container, and both declare a field called Volumes, but Config declares Volume as ``map[string]interface{}``, while Container declares Volume as ``map[string]string``.

The payload to the create container call is Config, but the response from the InspectContainer call is Container.

**Pull request closed without merging**
