### PR TITLE
Add support for Healthcheck.StartInterval (v1.44 API)

### PR DESCRIPTION
**Pull request by migesok**
https://docs.docker.com/engine/api/version-history/#v144-api-changes
https://docs.docker.com/engine/api/v1.44/#tag/Container/operation/ContainerCreate

I'm not good with golang but `make test` passes.

### CODE REVIEW

**Comment by migesok** [comment]
I'm trying to add --start-interval support to buildah and podman eventually.

**Review by fsouza — APPROVED** [review]
Thanks for contributing!

**Comment by migesok** [comment]
@fsouza thank you! Any plans for release?

**Comment by fsouza** [comment]
I wanted to try to get a solution for #1030 before cutting a new release, but realistically my time is fairly limited right now. I'll just cut a new release later today and come back to #1030 later.

**Comment by fsouza** [comment]
Done, just released v1.11.0!

**Comment by migesok** [comment]
@fsouza thank you very much!!!

**Pull request merged**
