### PR TITLE
refactor ParseEndpoint func

### PR DESCRIPTION
**Pull request by dalanlan**
Refactor to gain readability and conciseness.

### CODE REVIEW

**Comment by peter-edge** [comment]
just a quick thought: as long as you're doing this, this would be much clearer/more golang idiomatic (IMO) as a switch statement:

```go
switch u.scheme {
case "unix"
  return u, nil
case "http":
  fallthrough
case "https":
  fallthrough
case "tcp":
  ...
default:
  return nil, ErrInvalidEndpoint
}
```

what do you think?

**Comment by peter-edge** [comment]
oh, wait, you don't need those fallthroughs, i forgot:

```go
switch u.scheme {
case "unix"
  return u, nil
case "http", "https", "tcp":
  ...
default:
  return nil, ErrInvalidEndpoint
}
```

**Comment by fsouza** [comment]
Hi @dalanlan, thanks for contributing! I liked @peter-edge's idea, what do you think?

**Comment by dalanlan** [comment]
Make sense :) 
i did not think further at the very beginnig and will fix it later.

**Comment by dalanlan** [comment]
Updated. 
@fsouza

**Comment by fsouza** [comment]
@dalanlan thank you!

**Pull request merged**
