### PR TITLE
The url parameter must be coded

### PR DESCRIPTION
**Pull request by yiqguo**
The url parameter must be coded

### CODE REVIEW

**Comment by fsouza** [comment]
Hi @yiqguo, thanks for contributing! Can you fix the test as well?

**Comment by yiqguo** [comment]
@fsouza i'm so sorry!i forgot to test，now already fix.

**Comment by fsouza** [comment]
Hi @yiqguo, looks like something went wrong with the merge/rebase and now the pull request contains only the test, but not the code to make the test pass: https://travis-ci.org/fsouza/go-dockerclient/jobs/144351550#L342.

Can you take a look?

**Comment by yiqguo** [comment]
My local go version is go version go1.6.2 linux/amd64，my local without any error!!!You use is 1.7？

**Comment by fsouza** [comment]
@yiqguo please check the diff in the pull request: https://github.com/fsouza/go-dockerclient/pull/546/files.

You have the actual changes locally only, somehow.

**Pull request closed without merging**
