### PR TITLE
Updating volumes-from to be []string, not string

### PR DESCRIPTION
**Pull request by bfosberry**

### CODE REVIEW

**Comment by peter-edge** [comment]
This would break a lot of existing dependent code I would think, no?

**Comment by bfosberry** [comment]
Most likely! A better solution would be to use []string internally and do
remote api version detection, or abstract the type. Either way its going to
break some stuff. Hopefully we can get a plan in place to minimise damage.

**Comment by peter-edge** [comment]
In general, I don't think this repo has ever done a breaking change like that, is that correct, @fsouza? If we wanted to go that route, there should be more complete handling in place/implemented

**Comment by bfosberry** [comment]
The issue is its currently broken for me

**Comment by peter-edge** [comment]
This PR does more closely match the docker remote API https://docs.docker.com/reference/api/docker_remote_api_v1.19/#create-a-container, I think I have had this working in the past with CSV values but I could be wrong, that might have been another field

**Comment by bfosberry** [comment]
This whole thing smells of docker making a sublte breaking change

**Comment by peter-edge** [comment]
Ah ya, I did have it working haha https://github.com/peter-edge/go-dockerutils/blob/master/dockerutils.go#L174

**Comment by fsouza** [comment]
Hi @bfosberry @peter-edge, maybe Docker moved VolumesFrom from Config to HostConfig, so the value in Config doesn't do anything, because it doesn't exist in Docker's config: https://github.com/docker/docker/blob/master/runconfig/config.go#L117-L140.

They did it with security options, memory, swap and CPU shares as well. There are probably other cases.

I'd rather just document that VolumesFrom in go-dockerclient is deprecated, and users should specify it in the HostConfig type.

**Comment by peter-edge** [comment]
SGTM, ping @bfosberry do you want to do that in this PR?

**Comment by peter-edge** [comment]
Can we close this for now?

**Comment by fsouza** [comment]
@peter-edge yes, I'm closing it. Thanks!

**Comment by bfosberry** [comment]
I'll try that out on our side, thanks!

**Pull request closed without merging**
