### PR TITLE
fixes empty port bindings hostip

### PR DESCRIPTION
**Pull request by tcurdt**
Test are passing - just your formatting police doesn't seem to like the change.
But that's how docker uses it - so I suggest to change the formatting check instead.

### CODE REVIEW

**Comment by tcurdt** [comment]
fixes https://github.com/fsouza/go-dockerclient/issues/266

**Comment by fsouza** [comment]
Hey @tcurdt, thanks for contributing!

Please do not change the name of the attribute, just the struct tag. Changing the name of the attribute won't complain with the formatting police and will also break existing code.

Just this fix and we're good to go. Thanks again!

**Comment by fsouza** [comment]
BTW, as far as I can tell, Go does handle that (I will test it on master, but at least on Go 1.4 I'm sure it works). Which Go version you're running? I'm OK with fixing the struct tag, but maybe this won't fix the issue you're facing, have you tested it?

**Comment by fsouza** [comment]
Yeah, just tested and this code [1] always print "0.0.0.0 8080", both at Go 1.4 and Go tip. Can you confirm that this patch fixes the empty HostIP issue you're fighting?

[1] https://play.golang.org/p/pBxXqSIAR0

**Comment by tcurdt** [comment]
Changed as requested.
Just fixing the json/yaml mapping would mean a broken window though.

Hm. So casing doesn't actually matter? Urgh!
Then I am not quite sure what's happening and need to dig deeper.
I just found the discrepancy with docker and thought it was the problem.

In [my code](https://github.com/tcurdt/docker-upstream/blob/master/src/upstream/upstream.go#L115) I am getting a port but no IP. So far I cannot see a difference between the two except that `docker inspect` shows `HostIp` instead of `HostIP`.

I am on go 1.4.2.

**Comment by tcurdt** [comment]
OK. Found out what's going on.

The host IP actually really was empty in `HostConfig.PortBindings` (which can be solved by specifying it explicitly on the `docker run` command line). The better way to access the ip/ports would probably be `NetworkSettings.Ports`.

**Comment by tcurdt** [comment]
So I guess I'll just close the PR :)

**Pull request closed without merging**
