### PR TITLE
Events filters

### PR DESCRIPTION
**Pull request by stokito**
First three commits are from another PR #855
The PR add filtering to events and this is very important because there is a lot of events especially if containers have health checks.
I created EventsOptions but at this moment I have no idea how to support `since` and `until` criterias so I commented them out.

### CODE REVIEW

**Comment by fsouza** [comment]
Sorry I missed this. Will take a look tomorrow.

**Comment by stokito** [comment]
You can just cherry pick the last commit

**Comment by stokito** [comment]
Now the PR is ready to be merged.
I removed those commits with new Args type: instead used just plain `Filters map[string][]string`.
I kept logic with Since

**Review by fsouza — COMMENTED** [review]
One minor comment and a question about the proper API. Taking time would allow users to do something like:

```go
eventsOptions := docker.EventsOptions{
    Since:  time.Now().Add(-2 * time.Hour),
    Filters: map[string][]string{...},
}
```

Alternatively we could just take int64 which would be the unix timestamp (though that would make it difficult to differentiate between zero and unset).

**Comment by stokito** [comment]
Totally agree that time would be better than string. I keep it as a string for two reasons:
1. In other places we already using string for the `Since` field https://github.com/fsouza/go-dockerclient/blob/214a51d9a1e5c9cb0c69641f326c2d835820f35b/container_list.go#L16
2. Official docker client uses string and it can be a Duration or formatted RFC3339 date:
    * https://github.com/moby/moby/blob/5526afa2415bd3ee9b6878378247a9e07e44a7ef/api/types/client.go#L105
    * https://github.com/moby/moby/blob/master/client/events.go#L77
    * https://github.com/moby/moby/blob/5526afa2415bd3ee9b6878378247a9e07e44a7ef/api/types/time/timestamp.go#L26

Even while now we support only timestamp you may want to change this in future.

**Review by fsouza — APPROVED** [review]
Thanks for contributing!

**Pull request merged**
