### PR TITLE
Add GroupAdd option to HostConfig

### PR DESCRIPTION
**Pull request by swagiaal**
This add the GroupAdd support for the GroupAdd option which is part of
the v1.20 API

### CODE REVIEW

**Comment by swagiaal** [comment]
Hi @fsouza, could you please take a look at this ?

**Comment by pmorie** [comment]
@ncdc

**Comment by pmorie** [comment]
@swagiaal Seems like this field should be added to `TestInspectContainer` in container_test.go

**Comment by ncdc** [comment]
LGTM

**Comment by pweil-** [comment]
> LGTM

ditto

**Comment by swagiaal** [comment]
> @swagiaal Seems like this field should be added to TestInspectContainer in container_test.go
@pmorie added

**Comment by pmorie** [comment]
@swagiaal LGTM. 

@fsouza PTAL

**Comment by fsouza** [comment]
Thank you!

**Comment by swagiaal** [comment]
@fsouza thanks!

**Pull request merged**
