### PR TITLE
godep save -r ./...

### PR DESCRIPTION
**Pull request by freeformz**

### CODE REVIEW

**Comment by fsouza** [comment]
@freeformz did you open this pull request just to link the diff in tools/godep#224?

**Comment by peter-edge** [comment]
@fsouza I'm not completely sure on the background but I don't think this should be merged - we use a different vendoring tool, and the reason we didn't use godep was because it is hard to use go-dockerclient as a library across go versions if godep is used. Regardless, this just doubles the vendoring in here with what we do with party.

**Comment by freeformz** [comment]
@fsouza sorry about the noise.

**Comment by fsouza** [comment]
@freeformz no problem, I just wanted to get more context!

**Comment by freeformz** [comment]
@fsouza I would like to get some more clarity around your statements about godep vs party though at some point. But a private email for that is probably better (edward (at) heroku (dot) com) if you have a few minutes.

**Pull request closed without merging**
