### PR TITLE
Catching cases where bad auth is encoded

### PR DESCRIPTION
**Pull request by bfosberry**
Can someone pull and run tests for me, I can't get tests to pass fully, some issues with /tmp and whatnot

### CODE REVIEW

**Comment by peter-edge** [comment]
what is wrong with the tests? they would work universally, that would be worrisome

**Comment by bfosberry** [comment]
Keep in mind this is from a fork and running on linux

```
11:26:34-bfosberry~/.go/src/github.com/codeship/go-dockerclient (master)$ go test ./...
# github.com/codeship/go-dockerclient/external/github.com/Sirupsen/logrus
external/github.com/Sirupsen/logrus/entry_test.go:8:2: cannot find package "github.com/fsouza/go-dockerclient/external/github.com/stretchr/testify/assert" in any of:
	/usr/local/go/src/github.com/fsouza/go-dockerclient/external/github.com/stretchr/testify/assert (from $GOROOT)
	/home/bfosberry/.go/src/github.com/fsouza/go-dockerclient/external/github.com/stretchr/testify/assert (from $GOPATH)
FAIL	github.com/codeship/go-dockerclient/external/github.com/Sirupsen/logrus [setup failed]
ok  	github.com/codeship/go-dockerclient	1.885s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/opts	0.012s
--- FAIL: TestTarUntarWithXattr (0.00s)
	archive_test.go:648: operation not permitted
--- FAIL: TestUntarUstarGnuConflict (0.00s)
	archive_test.go:733: open testdata/broken.tar: no such file or directory
--- FAIL: TestTarWithBlockCharFifo (0.00s)
	archive_test.go:767: operation not permitted
breakoutError: "../victim/dotdot" is outside of "/tmp/docker-TestUntarInvalidFilenames273762702/dest"
breakoutError: lchown /tmp/docker-TestUntarInvalidFilenames269780373/dest/victim/slash-dotdot: operation not permitted
breakoutError: lchown /tmp/docker-TestUntarHardlinkToSymlink178606064/dest/symlink1: operation not permitted
--- FAIL: TestUntarHardlinkToSymlink (0.00s)
	archive_test.go:1012: i=0. open /tmp/docker-TestUntarHardlinkToSymlink178606064/dest/symlink1: no such file or directory
breakoutError: invalid hardlink "/tmp/docker-TestUntarInvalidHardlink765822607/victim/hello" -> "../victim/hello"
breakoutError: invalid hardlink "/tmp/docker-TestUntarInvalidHardlink983771810/victim/hello" -> "/../victim/hello"
breakoutError: invalid hardlink "/tmp/docker-TestUntarInvalidHardlink878304153/victim" -> "../victim"
breakoutError: invalid hardlink "/tmp/docker-TestUntarInvalidHardlink280259620/victim" -> "../victim"
breakoutError: invalid hardlink "/tmp/docker-TestUntarInvalidHardlink033097523/victim" -> "../victim"
breakoutError: invalid hardlink "/tmp/docker-TestUntarInvalidHardlink957370614/victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestUntarInvalidSymlink698404317/dest/dotdot" -> "../victim/hello"
breakoutError: invalid symlink "/tmp/docker-TestUntarInvalidSymlink086085528/dest/slash-dotdot" -> "/../victim/hello"
breakoutError: invalid symlink "/tmp/docker-TestUntarInvalidSymlink576537111/dest/loophole-victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestUntarInvalidSymlink919941770/dest/loophole-victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestUntarInvalidSymlink412940385/dest/loophole-victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestUntarInvalidSymlink056564300/dest/loophole-victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestUntarInvalidSymlink640833339/dest/dir/loophole" -> "../../victim"
--- FAIL: TestChangesWithChangesGH13590 (0.01s)
	changes_test.go:483: no change for expected change C /dir1/dir2/dir3
breakoutError: "../victim/dotdot" is outside of "/tmp/docker-TestApplyLayerInvalidFilenames563566728/dest"
breakoutError: open /tmp/docker-TestApplyLayerInvalidFilenames359275079/dest/victim/slash-dotdot: permission denied
breakoutError: invalid hardlink "/tmp/docker-TestApplyLayerInvalidHardlink542916858/victim/hello" -> "../victim/hello"
breakoutError: invalid hardlink "/tmp/docker-TestApplyLayerInvalidHardlink592183825/victim/hello" -> "/../victim/hello"
breakoutError: invalid hardlink "/tmp/docker-TestApplyLayerInvalidHardlink419380284/victim" -> "../victim"
breakoutError: invalid hardlink "/tmp/docker-TestApplyLayerInvalidHardlink565110379/victim" -> "../victim"
breakoutError: invalid hardlink "/tmp/docker-TestApplyLayerInvalidHardlink414512846/victim" -> "../victim"
breakoutError: invalid hardlink "/tmp/docker-TestApplyLayerInvalidHardlink361660373/victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestApplyLayerInvalidSymlink914164016/dest/dotdot" -> "../victim/hello"
breakoutError: invalid symlink "/tmp/docker-TestApplyLayerInvalidSymlink628739279/dest/slash-dotdot" -> "/../victim/hello"
breakoutError: invalid symlink "/tmp/docker-TestApplyLayerInvalidSymlink876232674/dest/loophole-victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestApplyLayerInvalidSymlink815448537/dest/loophole-victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestApplyLayerInvalidSymlink270366564/dest/loophole-victim" -> "../victim"
breakoutError: invalid symlink "/tmp/docker-TestApplyLayerInvalidSymlink785104755/dest/loophole-victim" -> "../victim"
FAIL
FAIL	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/archive	0.624s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/fileutils	0.004s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/homedir	0.005s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/ioutils	0.033s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/mflag	0.004s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/parsers	0.003s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/pools	0.005s
?   	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/promise	[no test files]
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/stdcopy	0.002s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/system	0.004s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/ulimit	0.002s
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/docker/pkg/units	0.002s
?   	github.com/codeship/go-dockerclient/external/github.com/docker/docker/volume	[no test files]
ok  	github.com/codeship/go-dockerclient/external/github.com/docker/libcontainer/user	0.004s
ok  	github.com/codeship/go-dockerclient/external/github.com/gorilla/context	0.004s
ok  	github.com/codeship/go-dockerclient/external/github.com/gorilla/mux	0.019s
ok  	github.com/codeship/go-dockerclient/external/github.com/opencontainers/runc/libcontainer/user	0.004s
ok  	github.com/codeship/go-dockerclient/testing	0.335s
```

**Comment by bfosberry** [comment]
I do get the same errors on fsouza/go-dockerclient master

**Comment by peter-edge** [comment]
Ya you can't do this like that with forks, but that's relatively universal with golang packages

```
cd $GOPATH/src/github.com/fsouza
rm -rf go-dockerclient
git clone https://github.com/codeship/go-dockerclient.git
```

**Comment by bfosberry** [comment]
Oh derp, make test not go test ./...

All is well

**Comment by peter-edge** [comment]
what was this fixing by the way? just for reference

**Comment by fsouza** [comment]
Thank you!

@peter-edge the problem was probably due to the fact that he was running ``go test ./...`` instead of ``make test``.

**Comment by bfosberry** [comment]
Yep. Also this is a bit of an edge case I came across by being a naughty boy and fiddling with the dockercfg

**Pull request merged**
