### PR TITLE
add client method to check credentials

### PR DESCRIPTION
**Pull request by daniel-garcia**
This PR adds a method for checking credentials.

https://docs.docker.com/reference/api/docker_remote_api_v1.18/#check-auth-configuration

### CODE REVIEW

**Comment by daniel-garcia** [comment]
ping @fsouza , any feedback on this PR?

**Comment by fsouza** [comment]
Hi @daniel-garcia, thanks for contributing and sorry about the delay. I was wondering whether we should read the body of the response and include it in the error message. According to the documentation, Docker will simply return 500 on failures, I think the reason of the failure will come in the body.

**Comment by daniel-garcia** [comment]
@fsouza, reading the body already happens on errors as part of Client.do()
https://github.com/fsouza/go-dockerclient/blob/master/client.go#L344

**Comment by fsouza** [comment]
@daniel-garcia what I meant is including the body in the error report, sorry. Something like:

```go
body, statusCode, err := c.do("POST", "/auth", doOptions{data: conf})
if err != nil {
	return err
}
if statusCode > 400 {
	return fmt.Errorf("auth error (%d): %s", statusCode, body)
}
```

**Comment by daniel-garcia** [comment]
@fsouza thanks for clarifying. I've updated the PR as you requested.

**Comment by fsouza** [comment]
Thank you! Sorry about the miscommunication.

**Pull request merged**
