### PR TITLE
Add MacAddress to NetworkSettings

### PR DESCRIPTION
**Pull request by paulbellamy**
It's both in Config, and in NetworkSettings.

### CODE REVIEW

**Comment by peter-edge** [comment]
Can you just link quickly to the location this is in github.com/docker/docker? There's been a duplication problem lately with these adds

**Comment by fsouza** [comment]
From what I know Docker, I suspect the field in the Config struct is for customizing the Mac address on container creation, and the field in NetworkSettings is for checking it later (in InspectContainer, for example).

@paulbellamy can you confirm that this is the case?

Thanks for contributing!

**Comment by paulbellamy** [comment]
I'm going based on the api documentation here: https://docs.docker.com/reference/api/docker_remote_api_v1.19/#inspect-a-container

**Comment by fsouza** [comment]
Indeed it exists in both places, as I've suspected before:

- Config: https://github.com/docker/docker/blob/967bc13ae68939c616033710f7695993aa4f5208/runconfig/config.go#L137
- NetworkSettings: https://github.com/docker/docker/blob/967bc13ae68939c616033710f7695993aa4f5208/daemon/network/settings.go#L24

I will merge this pull request, thank you very much for contributing!

**Comment by peter-edge** [comment]
ugh docker :)

**Pull request merged**
