### PR TITLE
Volume API Methods

### PR DESCRIPTION
**Pull request by peter-edge**
This is for https://github.com/docker/docker/pull/14242. @fsouza this is blazing new, and not even on the experimental.docker.com install yet (although probably will be in the next few days, when the date on https://apt.dockerproject.org/repo/ changes from August 26th to something newer, this will be there), but I need it for something I'm doing on the Pachyderm codebase - the goo.gl short links are directly to the documentation within https://github.com/docker/docker/blob/master/docs/reference/api/docker_remote_api_v1.21.md#24-volumes, but I will update those links without bothering you (ie without a PR :) ) when the documentation is up on docker's website, assumedly when 1.9.0 is released.

### CODE REVIEW

**Comment by flowlo** [comment]
Thanks @peter-edge! AFAIK volume plugins cannot be used via this client right now and so it would benefit greatly from exposing the volume API for custom volume driver awesomeness. Changes LGTM.

:cake:

**Comment by peter-edge** [comment]
@flowlo if you'd like even more of a head start, check out https://github.com/peter-edge/go-dockervolume  (get it with `go get -insecure go.pedge.io/dockervolume`), inspired by https://github.com/calavera/dkvolume but slightly different style.

**Comment by peter-edge** [comment]
and example usage (I haven't even used this yet, so I'm sure there's bugs) https://github.com/pachyderm/pachyderm/blob/master/src/cmd/pfs-volume-driver/main.go.

**Comment by flowlo** [comment]
@peter-edge I have [my (experimental) plugin ready](https://github.com/coduno/gcs-docker-volume) and use it with the CLI, just waiting for this to land to make use of it programmatically. :smile:

**Comment by peter-edge** [comment]
Ah look at that, you're already using dkvolume :) would love if you checked out go-dockervolume and let me know what you think of it :)

**Comment by flowlo** [comment]
Yup, just did not know of your plumbing lib. it looks cleaner tho, will switch when I have spare time.

**Comment by peter-edge** [comment]
Ya need to get that done, it's on a mental todo list :) let's move this out of the GitHub issue so poor @fsouza doesn't get too much spam :)

**Comment by peter-edge** [comment]
Asked what was going on with experimental builds over on https://github.com/docker/docker/issues/15968, but this shouldn't affect this PR, still ready for merge :)

**Comment by fsouza** [comment]
@peter-edge get a free SSL certificate with CloudFlare :-D

Regarding the PR, I'm just reviewing it, thanks!

**Comment by fsouza** [comment]
LGTM, thanks!

**Pull request merged**
